swagger: '2.0'
info:
  version: '1.0.0'
  title: Event Management API
  description: API for managing events
paths:
  /events:
    post:
      tags:
        - Events
      summary: Create a new event
      consumes:
        - application/json
      parameters:
        - in: body
          name: event
          description: The event to create
          schema:
            $ref: '#/definitions/CreateEventDto'
      responses:
        201:
          description: Event created successfully
        400:
          description: Invalid input
    get:
      tags:
        - Events
      summary: Get all events
      parameters:
        - in: query
          name: title
          type: string
          description: Filter events by title
        - in: query
          name: description
          type: string
          description: Filter events by description
        - in: query
          name: startAt
          type: string
          format: date-time
          description: Filter events by start date
        - in: query
          name: endAt
          type: string
          format: date-time
          description: Filter events by end date
        - in: query
          name: createdAt
          type: string
          format: date-time
          description: Filter events by creation date
      responses:
        200:
          description: A list of events
          schema:
            type: array
            items:
              $ref: '#/definitions/EventEntity'
  /events/{id}:
    get:
      tags:
        - Events
      summary: Get an event by id
      parameters:
        - in: path
          name: id
          type: string
          required: true
          description: The id of the event
      responses:
        200:
          description: An event
          schema:
            $ref: '#/definitions/EventEntity'
        404:
          description: Event not found
    put:
      tags:
        - Events
      summary: Update an event
      parameters:
        - in: path
          name: id
          type: string
          required: true
          description: The id of the event
        - in: body
          name: event
          description: The event data to update
          schema:
            $ref: '#/definitions/UpdateEventDto'
      responses:
        200:
          description: Event updated successfully
        400:
          description: Invalid input
        404:
          description: Event not found
    delete:
      tags:
        - Events
      summary: Delete an event
      parameters:
        - in: path
          name: id
          type: string
          required: true
          description: The id of the event
      responses:
        200:
          description: Event deleted successfully
        404:
          description: Event not found
  /calendar:
    get:
      tags:
        - Calendar
      summary: Get all events grouped by day
      responses:
        200:
          description: A list of events grouped by day
          schema:
            type: object
            $ref: '#/definitions/EventsByDayDto'
        404:
          description: No events found
          
definitions:
  EventsByDayDto:
   type: object
   additionalProperties: 
     type: array
     items:
       $ref: '#/definitions/EventEntity'
  CreateEventDto:
    type: object
    properties:
      title:
        type: string
      description:
        type: string
      startAt:
        type: string
        format: date-time
      endAt:
        type: string
        format: date-time
  UpdateEventDto:
    type: object
    properties:
      title:
        type: string
      description:
        type: string
      startAt:
        type: string
        format: date-time
      endAt:
        type: string
        format: date-time
  EventEntity:
    type: object
    properties:
      id:
        type: string
      title:
        type: string
      description:
        type: string
      startAt:
        type: string
        format: date-time
      endAt:
        type: string
        format: date-time
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time